# Generated by Django 5.1.1 on 2024-09-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_alter_event_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
