# Generated by Django 5.1.1 on 2024-09-21 04:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_alter_usercalendar_url_alter_usercalendar_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usercalendar",
            options={
                "verbose_name": "User Calendar",
                "verbose_name_plural": "User Calendars",
            },
        ),
        migrations.AlterUniqueTogether(
            name="usercalendar",
            unique_together={("user", "url")},
        ),
    ]
